# Generated by Django 4.2.4 on 2023-08-28 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Category title.', max_length=255)),
                ('is_published', models.BooleanField(default=False, help_text='Displayed to the user.')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(help_text='Food preview.', upload_to='food/%Y/%m/%d/')),
                ('title', models.CharField(help_text='Food title.', max_length=255)),
                ('composition', models.TextField(help_text='Composition of the food.')),
                ('description', models.TextField(help_text='Food description.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Food price', max_digits=10)),
                ('weight', models.PositiveIntegerField(help_text='Food weight in grams.')),
                ('proteins', models.DecimalField(decimal_places=1, help_text='Amount of proteins.', max_digits=6)),
                ('fats', models.DecimalField(decimal_places=1, help_text='Amount of fats.', max_digits=6)),
                ('carbohydrates', models.DecimalField(decimal_places=1, help_text='Amount of carbohydrates.', max_digits=6)),
                ('kilocalories', models.PositiveIntegerField(help_text='Amount of kilocalories.')),
                ('is_published', models.BooleanField(default=False, help_text='Displayed to the user.')),
                ('category', models.ForeignKey(help_text='Food category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='foods', to='foods.category')),
            ],
        ),
    ]
