# Generated by Django 4.2.4 on 2023-08-29 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(help_text='Promotion preview.', upload_to='promotion/%Y/%m/%d/')),
                ('title', models.CharField(help_text='Promotion title.', max_length=255)),
                ('description', models.TextField(help_text='Promotion description.')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Promotion start time.')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Promotion start time.')),
            ],
        ),
    ]
